server:
  port: 8080

spring:
  application:
    name: eb-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: eb-dev
      config:
        server-addr: localhost:8848
        namespace: eb-dev
        file-extension: yaml
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: eb-service-task
          uri: lb://eb-service-task
          predicates:
            - Path=/api/v1/task/**
          filters:
            - StripPrefix=0
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
