spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:eb_test;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
  data:
    redis:
      host: localhost
      port: 6379
  sql:
    init:
      mode: never

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.enterprise.brain.task.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.enterprise.brain.task: debug
