-- 补退料申请明细表 DB_MATERIAL_CALL_ITEM 增加物料行备注/责任归属列
-- FEntrtyMemo  (v1.1) 物料行备注，写入金蝶 K3Cloud 生产退料单分录备注字段，NVARCHAR(200)
-- responsible  (v1.2) 责任归属，质检审核环节手填，M6 写入金蝶生产退料单分录自定义字段 Fresponsible，NVARCHAR(100)
-- 幂等：列已存在则跳过

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'DB_MATERIAL_CALL_ITEM' AND COLUMN_NAME = 'FEntrtyMemo'
)
BEGIN
    ALTER TABLE dbo.DB_MATERIAL_CALL_ITEM ADD FEntrtyMemo NVARCHAR(200) NULL CONSTRAINT DF_DBMCI_FEntrtyMemo DEFAULT('');
    PRINT '[OK] FEntrtyMemo 列已添加，默认空串';
END
ELSE
    PRINT '[SKIP] FEntrtyMemo 列已存在';
GO

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'DB_MATERIAL_CALL_ITEM' AND COLUMN_NAME = 'responsible'
)
BEGIN
    ALTER TABLE dbo.DB_MATERIAL_CALL_ITEM ADD responsible NVARCHAR(100) NULL CONSTRAINT DF_DBMCI_responsible DEFAULT('');
    PRINT '[OK] responsible 列已添加，默认空串';
END
ELSE
    PRINT '[SKIP] responsible 列已存在';
GO

-- 验证
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'DB_MATERIAL_CALL_ITEM' AND COLUMN_NAME IN ('FEntrtyMemo', 'responsible');
GO
