-- 补退料申请单头表 DB_MATERIAL_CALL 增加归属组织/组别列
-- FORG    归属组织, 发起人提交时填写, 金蝶生产退料单头统计字段 Forg, NVARCHAR(20)
-- F_GROUP 组别, 发起人提交时填写, 金蝶生产退料单头统计字段 FGroup, NVARCHAR(50)
-- 两字段仅用于金蝶侧统计报表, 选填可空, 原样透传不校验
-- 注意: FInspector(质检员) 复用已有 QC_STAFF_NAME, 不新增列
-- 幂等：列已存在则跳过

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'DB_MATERIAL_CALL' AND COLUMN_NAME = 'FORG'
)
BEGIN
    ALTER TABLE dbo.DB_MATERIAL_CALL ADD FORG NVARCHAR(20) NULL;
    PRINT '[OK] FORG 列已添加';
END
ELSE
    PRINT '[SKIP] FORG 列已存在';
GO

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'DB_MATERIAL_CALL' AND COLUMN_NAME = 'F_GROUP'
)
BEGIN
    ALTER TABLE dbo.DB_MATERIAL_CALL ADD F_GROUP NVARCHAR(50) NULL;
    PRINT '[OK] F_GROUP 列已添加';
END
ELSE
    PRINT '[SKIP] F_GROUP 列已存在';
GO

-- 验证
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'DB_MATERIAL_CALL' AND COLUMN_NAME IN ('FORG', 'F_GROUP');
GO
