SELECT ORDINAL_POSITION, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, IS_NULLABLE, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'mes_dwd_productOrder' AND COLUMN_NAME = 'BOMflag';
GO
SELECT TOP 3 id, pcode, materialid, BOMflag FROM mes_dwd_productOrder;
GO
